services:
  Controller\BaseController:
    abstract: true
    public: false
    calls:
      - [setRequest, ['@request_stack']]

  Controller\DefaultController:
    public: true
    parent: Controller\BaseController

  Controller\AuthController:
    parent: Controller\BaseController
    arguments:
      - '@user.model'
      - '@security.token_storage'
      - '@session'
      - '@event_dispatcher'
    public: true

  Controller\Admin\UserController:
    parent: Controller\BaseController
    arguments:
      - '@user.model'
    public: true
