services:
  abstract.model:
    class: Domain\Shared\Model\AbstractModel
    public: true

  user.model:
    class: Domain\User\Model\UserModel
    parent: abstract.model
    arguments:
      - '@user.repo'
    public: true

  training.model:
    class: Domain\Training\Model\TrainingModel
    parent: abstract.model
    arguments:
      - '@training.repo'
    public: true

  training.user.model:
    class: Domain\Training\Model\TrainingUserModel
    parent: abstract.model
    arguments:
      - '@training.user.repo'
    public: true
