services:
  app.session:
    class: Application\Handlers\Session
    arguments:
      - '%database_host%'
      - '%database_name%'
      - '%database_user%'
      - '%database_password%'

  register.consumer:
    class: Infrastructure\Consumers\RegisterConsumer
    arguments:
      - '@swiftmailer.mailer.default'
      - '@twig'
    public: true
