services:
  app.session:
    class: Application\Handlers\Session
    arguments:
      - '%database_host%'
      - '%database_name%'
      - '%database_user%'
      - '%database_password%'

  send.consumer:
    class: Infrastructure\Consumers\SendConsumer
    arguments:
      - '@email.sender'
    public: true

  abstract.sender:
    class: Infrastructure\Senders\AbstractSender
    public: true
    abstract: true
  email.sender:
    class: Infrastructure\Senders\EmailSender
    arguments:
      - '@swiftmailer.mailer.default'
      - '@twig'
    public: true
    parent: abstract.sender
