services:
  app.exception_listener:
    class: Application\Listeners\ExceptionListener
    arguments:
      - '@domain.logger'
      - '@twig'
      - '%kernel.environment%'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  domain.logger_handler:
    class:     Monolog\Handler\StreamHandler
    arguments:
      - '%kernel.logs_dir%/%kernel.environment%.log'

  domain.logger:
    class:     Symfony\Bridge\Monolog\Logger
    arguments:
      - 'app'
    calls:
      - ['pushHandler', [ '@domain.logger_handler']]
      -
  app.session:
    class: Application\Handlers\Session
    arguments:
      - '%database_host%'
      - '%database_name%'
      - '%database_user%'
      - '%database_password%'

  send.consumer:
    class: Infrastructure\Consumers\SendConsumer
    arguments:
      - '@email.sender'
      - '@sms.sender'
      - '@training.user.repo'
    public: true

  abstract.sender:
    class: Infrastructure\Senders\AbstractSender
    public: true
    abstract: true

  email.sender:
    class: Infrastructure\Senders\EmailSender
    arguments:
      - '@swiftmailer.mailer.default'
      - '@twig'
    public: true
    parent: abstract.sender

  sms.sender:
    class: Infrastructure\Senders\SmsSender
    public: true
    parent: abstract.sender
