doctrine:
    dbal:
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Domain/User/Mapping'
                prefix: 'Domain\User\Entity'
                alias: User
            Training:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Domain/Training/Mapping'
                prefix: 'Domain\Training\Entity'
                alias: Training
            Session:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Domain/Session/Mapping'
                prefix: 'Domain\Session\Entity'
                alias: Session
