old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        register:
            connection: default
            exchange_options:
              name: 'register'
              type: direct
    consumers:
        register:
            connection: default
            exchange_options:
              name: 'register'
              type: direct
            queue_options:
              name: 'register'
            callback: register.consumer
