old_sound_rabbit_mq:
    connections:
        default:
          host: '%rabbitmq_host%'
          user: '%rabbitmq_user%'
          password: '%rabbitmq_password%'
          vhost: '%rabbitmq_vhost%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        send:
            connection: default
            exchange_options:
              name: 'send'
              type: direct
    consumers:
        send:
            connection: default
            exchange_options:
              name: 'send'
              type: direct
            queue_options:
              name: 'send'
            callback: send.consumer
