monolog:
    handlers:
        php:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%_php.log'
            level: debug
            channels: [php]
        doctrine:
            channels: doctrine
            type: stream
            path:  '%kernel.logs_dir%/%kernel.environment%_doctrine.log'
            level: debug
        security:
            channels: security
            type: stream
            path:  '%kernel.logs_dir%/%kernel.environment%_security.log'
            level: debug
        request:
            channels: request
            type: stream
            path:  '%kernel.logs_dir%/%kernel.environment%_request.log'
            level: debug
        app:
            channels: app
            type: stream
            path:  '%kernel.logs_dir%/%kernel.environment%_app.log'
            level: debug
        console:
            channels: console
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_console.log'
            level: debug
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_all.log'
            level: debug
            channels: ['!event', '!php']
