index:
    path: /
    controller: Controller\DefaultController::index

login:
    path: /login
    controller: Controller\AuthController::login
    methods: [GET, POST]
logout:
    path: /logout
    controller: Controller\AuthController::logout
    methods: [GET, POST]

register:
  path: /register
  controller: Controller\AuthController::register
  methods: [GET, POST]

admin.user.list:
  path: /admin/user
  controller: Controller\Admin\UserController::getList
  methods: [GET]

admin.user.edit:
  path: /admin/user/form/{id?}
  controller: Controller\Admin\UserController::form
  methods: [GET, POST]
  requirements:
    id: '\d+'
