index:
    path: /
    controller: Controller\DefaultController::index

login:
    path: /login
    controller: Controller\AuthController::login
    methods: [GET, POST]

logout:
    path: /logout
    controller: Controller\AuthController::logout
    methods: [GET, POST]

confirmation:
    path: /confirmation/{activateCode}
    controller: Controller\AuthController::confirmation
    methods: [GET, POST]

register:
  path: /register
  controller: Controller\AuthController::register
  methods: [GET, POST]

admin.routes:
  resource: 'routes/admin'
  type: directory
  prefix: '/admin'

user.routes:
  resource: 'routes/user'
  type: directory
  prefix: '/user'

