#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: Controller\AuthController::login
    methods: [GET, POST]
register:
  path: /register
  controller: Controller\AuthController::register
  methods: [GET, POST]
