Domain\Training\Entity\TrainingUser:
  type: entity
  id:
    userId:
      type: integer
      options:
        unsigned: true
    trainingId:
      type: integer
      options:
        unsigned: true

  fields:
    subscriptionType:
      type: integer
      options:
        unsigned: true
    createdAt:
      type: datetime


  manyToOne:
    user:
      targetEntity: Domain\User\Entity\User
      inversedBy: trainings
      joinColumn:
        name: user_id
        referencedColumnName: id
    training:
      targetEntity: Domain\Training\Entity\Training
      inversedBy: trainings
      joinColumn:
        name: training_id
        referencedColumnName: id
