Domain\Training\Entity\Training:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true

  fields:
    name:
      type: string
      length: 150
    trainerName:
      type: string
      length: 150
    description:
      type: text
      nullable: true
    createdAt:
      type: datetime
    updatedAt:
      type: datetime

  oneToMany:
    trainings:
      targetEntity: Domain\Training\Entity\TrainingUser
      mappedBy: training
